### ISSUE TITLE
Автоматическая подстановка диагноста

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#100]
Сделать автоматическую подстановку диагноста, при создании рекомендации, если хотя бы один раз диагност указывался.

**Comment by grachevko** [comment]
Рекомендации привязаны к машине, а не к заказу и могут быть созданы чёрт знает когда и диагност тот может быть давно уволен.

**Comment by KCH0000** [comment]
Имеется ввиду в текущем моменте. Если мастер добавил рекомендацию, указа диагноста, то следующей поставить автоматически. Типа добавлена "Сегодня" , диагност "Петя"
