### ISSUE TITLE
Доработка диагноста

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#103]
Возникает такая ситуация, что человек диагностировался не у нас, а присылает список для проценки.
Мы оформляем заказ с проценкой, но приходится указывать диагноста при этом диагностики не было.
Предлагаю два варианта
1. Добавить "По словам клиента" или "Сторонняя организация"
2. Сделать поле не обязательным, но  это дыра.

**Comment by grachevko** [comment]
Создай организацию "Сторонняя организация" и пометь что она "Подрядчик". Она появится в выборе диагноста
