### ISSUE TITLE
Создание заказа без машины

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#104]
Сделать возможность создавать заказ без машины. Сейчас когда выбираешь клиента, у которого есть машина, то нельзя ее брать и создать просто на клиента.

**Comment by grachevko** [comment]
На самом деле там есть пустое значение.
Надо как то туда текст написать

![image](https://user-images.githubusercontent.com/8628465/45633406-5fd70800-baa8-11e8-8edd-0c05a344733b.png)
