### ISSUE TITLE
Добавить костыль с кассой

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#105]
Когда создается ручная проводка, сделать галочку  "Учитывать в кассе"
Когда галочка стоит проводка учитывается в расчете галочки, если не стоит, то не учитывается
По умолчанию галочка стоит.

**Comment by grachevko** [comment]
А теперь ещё раз и по русски

**Comment by KCH0000** [comment]
Я создал проводку -1000 рублей на покупку пиццы
Проводка в костыльном === Расходы создалась, но Касса в шапке от этого не уменьшилась.
Хочется, чтобы была возможность уменьшать кассу и было обоснование, т.к. сейчас нет счетов, то нужно возродить старый костыль.
