### ISSUE TITLE
Неправильная обработка зч в закупках

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#1104]
Если в заказ добавить запчасть, но при этом не делать резерв, то запчасть все равно попадает в закупки.
![image](https://user-images.githubusercontent.com/28162151/108035222-b1a06580-7047-11eb-8904-1a5e284ce8ab.png)
![image](https://user-images.githubusercontent.com/28162151/108035242-b7964680-7047-11eb-9dcb-d22d20ba10a8.png)

**Comment by grachevko** [comment]
Наличие открытого заказа с запчастью = потенциальный расход

Функционал резерва выполняет задачу резерва и с закупками никак не связан

**Comment by KCH0000** [comment]
Тогда нужно выпиливать механизм, который позволяет выводить из резерва при при добавлении в заказ. Вывод из резерва это сознательное решение менеджера указать, что запчасть не должна учитываться, как потенциально расходная, а добавление в резерв, это сознательное решение указать, что будет потенциальный расход.

**Comment by grachevko** [comment]
> который позволяет выводить из резерва при добавлении в заказ

Что это за механизм? У нас автоматический резерв при добавлении в заказ, вывода из резерва вроде нет автоматического

**Comment by grachevko** [comment]
> Вывод из резерва это сознательное решение менеджера указать, что запчасть не должна учитываться, как потенциально расходная

Резерв это про закрепление запчасти за конкретным заказом/клиентом, никакого отношения к потенциальным расходным оно не имеет

**Comment by KCH0000** [comment]
Получается добавление в черновик запчасти, либо предварительный заказ для клиента который приедет через полгода должно давать указание для заказа запчасти прям сейчас и замораживания денег на складе?
Или работа с клиентом которая может длится несколько дней с итогом в виде закрытия заказы без реального заказа (клиент отказался) уже дало указание - заказать запчасть на склад и в итоге опять оно будет там лежать до второго пришестивия? Кто вообще ввел это понятие "потенциальный расход" и почему оно дает не потенциальный заказ запчасти, а прямое указание заказать прям сейчас?

**Comment by grachevko** [comment]
> Получается добавление в черновик запчасти, либо предварительный заказ

Предложения ввести понятия черновой/предварительный/проценка заказ были отклонены, поэтому все заказы всегда были и пока остаются боевыми

Собственно от сюда и все проблемы

**Comment by KCH0000** [comment]
Смысла обсуждать дальше эту хуйни нет, поработаем с багами
