### ISSUE TITLE
Разрешить редактировать карточку товара

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#115]
На данный момент нельзя изменить производителя и номер.
Нужно разрешить редактирование.

**Comment by grachevko** [comment]
Это потенциальная дыра. Смена номера и производителя делает из одной запчасти другую. 
Такой операцией можно легко превратить базу в мусор. 
Если требуется исправить ошибку, то подобная возможность должна быть только у ограниченного круга лиц.

**Comment by KCH0000** [comment]
Согласен на такое решение.
