### ISSUE TITLE
Дата ожидания по записи

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#119]
При выборе статуса Ожидание по записи предлагать указать дату записи
Статус становится серым
В день приезда статус становится синим
Если текущая дата больше  и статус не поменялся, то красим в красный.

**Comment by grachevko** [comment]
Лучше сделать кнопку "Записать клиента", и сам факт записи поменяет статус

**Comment by KCH0000** [comment]
Можно сделать кнопку записать клиента, не важно. Важно уведомлять администратора о том, что киента ожидался, но по каким либо причинам заказ еще активен
