### ISSUE TITLE
Неактивно после поиска производителя при добавлении запчасти из заказа

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#129]
Поле есть, но курсор туда не встает

**Comment by grachevko** [comment]
Не понял как воспроизвести

**Comment by KCH0000** [comment]
![image](https://user-images.githubusercontent.com/28162151/46485495-713c4600-c804-11e8-9066-f014914de90a.png)
Заходим в заказ
Нажимаем добавить ЗЧ
Нажимаем +
Выбираем производителя
Пытаемся поставить курсор
Сосем за обе щеки

**Comment by grachevko** [comment]
У меня не воспроизводится, всё выбирается, запчасть создаётся.
