### ISSUE TITLE
Проверка корректности заказа

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#131]
1. Применять фон розовым если стоимость запчасти меньше 50. При наведении показывать сообщение "Возможно указана неверная цена"

2. Производить расчет средней отпускного кол-ва позиции. Если в заказе указано кол-во меньше чем 75% от расчетного кол-ва, то применять фон строки розовым. При наведении показывать сообщение
"Возможно указано неверное кол-во"

**Comment by grachevko** [comment]
Текущий алгоритм определения рекомендованной цены:

Берётся наибольшая цена из:
- Цена в справочнике запчастей
- Цена из последней поставки + наценка 15%
- Цена последней проданной запчасти

Ячейка с ценой подсвечивается красным если рекомендованная цена больше отпускной, плюс выводится рекомендованная цена.

Так же ячейка окрашивается красным если отпускная цена 0.
