### ISSUE TITLE
Автоматическое применение кузовов для автомобилей Ниссан

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#133]
Для всех VINов nissan произвести попытку применить кузов
Кузов в вине Ниссан указывается  с 7 по 9 символ. Если есть уникальное соответсвие с кузовом в базе, то применять этот кузов.
После вывести список винов, для которых применить не удалось 
http://nissan-part.ru/index.php?option=info&view=vin

**Comment by grachevko** [comment]
Получение кузовов, для которых не удалось применить 
```sql
SELECT DISTINCT SUBSTR(vin, 7, 3)
FROM car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
LEFT JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 7, 3)
WHERE LENGTH(vin) = 17
AND model2.id IS NULL;
```

Найти соответствие и применить кузов
```sql
UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 7, 3)
SET car.car_model_id = model2.id
WHERE LENGTH(vin) = 17;
```

Не найденные соответствия на текущий момент
```
5Y5
5Y7
7YX
C23
5Y0
Y61
740
B14
J30
A32
1A4
1E8
K11
P11
P10
A5X
d21
R20
DJA
LMS
N15
LAS
LM5
KFA
V10
000
010
110
100
J1O
MJ1
8W7
8W8
8W2
8W6
8W9
8W3
8W5
8W4
8U6
8U3
8u9
D22
B17
```

**Comment by KCH0000** [comment]
KNMCSSLAS6P606702 -> KNMCSHLAS6P606702
SJNFBAJ1OU1041658 -> SJNFBAJ10U1041658
SJNFBNJ1OU2300211 -> SJNFBNJ10U2300211
SJNNFBMJ11U145959 -> SJNFBMJ11U1459590

**Comment by KCH0000** [comment]
UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 7, 3)
                       SET car.car_model_id = model2.id
                       WHERE LENGTH(vin) = 17;

UPDATE car
SET vin = 'KNMCSHLAS6P606702'
WHERE vin = 'KNMCSSLAS6P606702';

UPDATE car
SET vin = 'KNMCSHLMS7P676252'
WHERE vin = 'KMNSCHLMS7P676252';

UPDATE car
SET vin = 'SJNFBAJ10U1041658'
WHERE vin = 'SJNFBAJ1OU1041658';

UPDATE car
SET vin = 'SJNFBNJ10U2300211'
WHERE vin = 'SJNFBNJ1OU2300211';

UPDATE car
SET vin = 'SJNFBMJ11U1459590'
WHERE vin = 'SJNNFBMJ11U145959';

UPDATE car
SET car.car_model_id = 2030
WHERE vin LIKE 'KNMCSHL%';

UPDATE car
SET car.car_model_id = 2041
WHERE vin LIKE 'JN8AZ08W%';

UPDATE car
SET car.car_model_id = 2042
WHERE vin LIKE 'JN8AZ18W%';

UPDATE car
SET car.car_model_id = 2040
WHERE SUBSTR(vin, 6, 3) IN ('L00', 'L01', 'L10', 'L11');

UPDATE car
SET car.car_model_id = 2075
WHERE vin LIKE 'JN8CY15Y%';

UPDATE car
SET car.car_model_id = 2076
WHERE vin LIKE 'JN8AR0%';

UPDATE car
SET car.car_model_id = 2080
WHERE vin LIKE '5N1BV28U%';

UPDATE car
SET car.car_model_id = 2066
WHERE vin LIKE 'JN1CA31A4YT013978';

UPDATE car
SET car.car_model_id = 2086
WHERE vin LIKE '1N4BA41E84C879667';

UPDATE car
SET car.car_model_id = 2054
WHERE vin LIKE 'Z8NHSNDJA53314023';

SELECT DISTINCT vin
FROM car
       JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
       LEFT JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 7, 3)
WHERE LENGTH(vin) = 17
  AND model2.id IS NULL
  AND car.car_model_id < 2029;

**Comment by KCH0000** [comment]
после удалить все ниссаноские кузова с id > 2029

**Comment by KCH0000** [comment]
use db;

UPDATE car
  JOIN car_model model on car.car_model_id = model.id AND model.manufacturer_id = 36
SET vin = REPLACE(vin, '-', '');

UPDATE car
JOIN car_model model on car.car_model_id = model.id AND model.manufacturer_id = 36
SET vin = REPLACE(vin, ' ', '');


UPDATE car
SET vin = 'KNMCSHLAS6P606702'
WHERE vin = 'KNMCSSLAS6P606702';

UPDATE car
SET vin = '3N1FCAC11UK541712'
WHERE vin = '3N1FCAС11UK541712';

UPDATE car
SET vin = 'KNMCSHLMS7P676252'
WHERE vin = 'KMNSCHLMS7P676252';

UPDATE car
SET vin = 'SJNFBAJ10U1041658'
WHERE vin = 'SJNFBAJ1OU1041658';

UPDATE car
SET vin = 'SJNFBNJ10U2300211'
WHERE vin = 'SJNFBNJ1OU2300211';

UPDATE car
SET vin = 'SJNFBMJ11U1459590'
WHERE vin = 'SJNNFBMJ11U145959';

UPDATE car
SET vin = 'VSKJVWR51U0438160'
WHERE vin = 'VSJVWR51U0438160';

UPDATE car
SET vin = 'JN1CCUA33U0084048'
WHERE vin = 'JNCCUA33U0084048';

UPDATE car
SET vin = 'JN1CCUA33U0092385'
WHERE vin = 'JN1CCU33U0092385';

UPDATE car
SET vin = 'JN1BAUJ31U0302257'
WHERE vin = 'JNBAUJ31U0302257';

UPDATE car
SET vin = 'SJNBAAP12U0204073'
WHERE vin = 'SJBAAP12U0204073';

UPDATE car
SET vin = 'SJNBCAP12U0222709'
WHERE vin = 'SJNBCAP12U022709';

UPDATE car
SET vin = 'SJNBAAP12U0240612'
WHERE vin = 'SJNBAP12U0240612';

UPDATE car
SET vin = 'SJNBBAN16U2656122'
WHERE vin = 'SJNBBAN16U265612';

UPDATE car
SET vin = 'SJNBBAN16U0464977'
WHERE vin = 'SJNBBAN16U464977';

UPDATE car
SET vin = 'KNMCSHLMS6P619670'
WHERE vin = 'KNMSHLMS6P619670';

UPDATE car
SET vin = 'KNMCSHLMS7P661305'
WHERE vin = 'KNMSHLMS7P661305';

UPDATE car
SET vin = 'KNMCSHLAS9P751529'
WHERE vin = 'KNMSHLAS9P751529';

UPDATE car
SET vin = 'SJNFBAJ10U1314359'
WHERE vin = 'SJNFAJ10U1314359';

UPDATE car
SET vin = 'SJNFBNJ10U1392507'
WHERE vin = 'SJNFBNJ10U392507';

UPDATE car
SET vin = 'SJNFBNJ10U1289306'
WHERE vin = 'SJNFNJ10U1289306';

UPDATE car
SET vin = 'SJNFBNJ10U1106927'
WHERE vin = 'SJNFBN10U1106927';

UPDATE car
SET vin = 'SJNFBAJ10U2000512'
WHERE vin = 'SJNFBAJ10U200512';

UPDATE car
SET vin = 'SJNFBNJ10U1249334'
WHERE vin = 'SJNFBNJ10U124933';

UPDATE car
SET vin = 'SJNFBNJ10U1440440'
WHERE vin = 'SJNFBNJ10U144044';

UPDATE car
SET vin = 'Z8NTANZ51DS020797'
WHERE vin = 'Z8NTAZ51DS020797';

UPDATE car
SET vin = 'JN1TBNT31U0007705'
WHERE vin = 'JN1TBT31U0007705';

UPDATE car
SET vin = 'SJNBBAN16U0506753'
WHERE vin = 'SJBBAN6U0506753';

UPDATE car
SET vin = 'JN1CCUA32U0004700'
WHERE vin = 'JN1CCUA32U00047';

UPDATE car
SET vin = 'KNMCSHLMS8P704466'
WHERE vin = 'KNMSHLS8P70466';

UPDATE car
SET vin = 'SJNFBNJ10U1336870'
WHERE vin = 'SJFBN10U133687';

UPDATE car
SET vin = 'SJNBAAP12U1304366'
WHERE vin = 'SJBAA12U30436';


UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 7, 3)
SET car.car_model_id = model2.id
WHERE LENGTH(vin) = 17;

UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 4, 3)
SET car.car_model_id = model2.id
WHERE LENGTH(vin) =12;

UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 3, 3)
SET car.car_model_id = model2.id
WHERE LENGTH(vin) =11;

UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 2, 3)
SET car.car_model_id = model2.id
WHERE LENGTH(vin) =10;

UPDATE car
JOIN car_model model ON car.car_model_id = model.id AND model.manufacturer_id = 36
JOIN car_model model2 ON model2.case_name = SUBSTR(vin, 1, 3)
SET car.car_model_id = model2.id
WHERE LENGTH(vin) =9;

UPDATE car
SET car.car_model_id = 2030
WHERE vin LIKE 'KNMCSHL%';

UPDATE car
SET car.car_model_id = 2041
WHERE vin LIKE 'JN8AZ08W%';

UPDATE car
SET car.car_model_id = 2042
WHERE vin LIKE 'JN8AZ18W%';

UPDATE car
SET car.car_model_id = 2040
WHERE SUBSTR(vin, 6, 3) IN ('L00', 'L01', 'L10', 'L11');

UPDATE car
SET car.car_model_id = 2075
WHERE vin LIKE 'JN8CY15Y%';

UPDATE car
SET car.car_model_id = 2076
WHERE vin LIKE 'JN8AR0%';

UPDATE car
SET car.car_model_id = 2080
WHERE vin LIKE '5N1BV28U%';

UPDATE car
SET car.car_model_id = 2066
WHERE vin LIKE 'JN1CA31A4YT013978';

UPDATE car
SET car.car_model_id = 2086
WHERE vin LIKE '1N4BA41E84C879667';

UPDATE car
SET car.car_model_id = 2054
WHERE vin LIKE 'Z8NHSNDJA53314023';

UPDATE car
SET car.car_model_id = 2073
WHERE id = 1827;

UPDATE car
SET car.car_model_id = 2033
WHERE id = 241;

UPDATE car
SET car.car_model_id = 2103
WHERE id = 847;

UPDATE car
SET car.car_model_id = 2104
WHERE id = 2562;

UPDATE car
SET car.car_model_id = 2107
WHERE id = 1060;


SELECT c.id, vin, length(vin), c.car_model_id, c.owner_id FROM car c
  jOIN car_model model on c.car_model_id = model.id AND model.manufacturer_id = 36
WHERE car_model_id < 2029;

DELETE FROM car_model
WHERE manufacturer_id = 36 AND id < 2029;
