### ISSUE TITLE
Индикатор, что машина находится на стоянке в сервисе

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#134]
Добавить атрибут, что машина находится в сервисе.
Для оператора механизм должен называться "Машина находится на стоянке" 
В заказе и списке заказов выводить "Стоянка" на фоне варнинг.

**Comment by grachevko** [comment]
Именно на стоянке или вообще в сервисе?

**Comment by KCH0000** [comment]
Дублирующая фича.

**Comment by grachevko** [comment]
Если дублирующая надо при закрытии указывать ссылку на оригинал
