### ISSUE TITLE
Автоматическая корректировка стоимости запчасти

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#135]
Если в заказе стоимость закрытия больше стоимости указанной в нуменклатуре, то к нуменклатуре применить стоимость закрытия.

**Comment by grachevko** [comment]
што?

**Comment by KCH0000** [comment]
Пример.
У запчасти цена в карточке стоит 2700,
В заказе менеджер вбивает запчасть и видит, что цена слишком устарела и продает за 2900. 
В данном случает и дальше будет продавать зч по этой цене, но для того, чтобы новая цена изменилась нужно зайти в карточку товара  и там установить цену, что очень не удобно, особенно если речь идет о товаре, которой продается редко.
Предлагаю сделать так.
Если в заказе вбили новую цену и она больше на 5-15% процентов, то в карточке товара устанавливается новая цена.
После установки новой цены, появляется варниг, что установлена новая цена.
Работать должно только на повышение цены.

**Comment by grachevko** [comment]
Про 5-15% какая то хрень. Может просто смотреть что цена выше и всё?

**Comment by KCH0000** [comment]
Потому что если меньше это корректировка под конкретны заказ, если больше это пидору заградительную цену поставили.  Но ограничение и с низу и сверху полюбос должно быть. А проценты уже надо будет из статистики смотреть.

**Comment by grachevko** [comment]
Нужно понимание откуда брать %

**Comment by KCH0000** [comment]
Идея не жизнеспособна. Нужно двигаться к справочнику работа с привязкой к комплектации.
