### ISSUE TITLE
Не отображается прошлый пробег при создании заказа

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#141]
На странице создания заказа над полем "Пробег" раньше был последний пробег, теперь его нет.
Очень нужен.

**Comment by grachevko** [comment]
На странице "создания" заказа никогда пробега не было, ибо при открытии этой страницы у нас ещё нет автомобиля. 
Максимум могу попробовать добавить при редактировании и то если машина была уже выбрана. 
Старый пробег показывается на странице визарда перед финалкой
