### ISSUE TITLE
Скидки

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#164]
Скидочная система.

1. Постоянная скидка на товар.
Скида устанавливается в карточке товара и она применяется автоматически при добавлении такого товара в заказ. 
![default](https://user-images.githubusercontent.com/28162151/51181132-61d89880-18db-11e9-8f0a-cad78843b5bb.png)
В режиме редактирования появляется поле "Постоянная скидка". 
![default](https://user-images.githubusercontent.com/28162151/51181350-fe9b3600-18db-11e9-8dc3-7be38638eaf4.png)

2. Скидки устанавливающиеся в заказах.
Устанавливается скидка отдельно для каждой работы и для каждой запчасти
Шапка заказ наряда выглядит так
![default](https://user-images.githubusercontent.com/28162151/51182345-ec6ec700-18de-11e9-8d89-ed5c366f6ed5.png)
Часть заказ наряда
![default](https://user-images.githubusercontent.com/28162151/51182942-d8c46000-18e0-11e9-9092-8d9fd8bc5128.png)

В столбце скидка указывается сумму скидки и процент скидки.
В столбце Цена указывается цена с учетом скидки, аналитика происходит по цене со скидкой
В столбце Итого указывается цена с учетом скидки.

**Comment by grachevko** [comment]
Вторую часть открыть в отдельной задаче, если она будет актуальна
