### ISSUE TITLE
Отчет по продажам за период

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#184]
Пользователь выбирает период, ему выдаютя все продажи ЗЧ сгруппированными по ЗЧ, плюс остаток на складе.

**Comment by KCH0000** [comment]
По запросу /motions/sell/:start_date/:end_date/
выдавать JSON со списаниями на складе зч.
{id(зч), date(дата списания), кол-во, кузов если есть }

**Comment by grachevko** [comment]
1 ч. https://github.com/automagistre/automagistre/commit/6eb4a531555ba3f1ed1021887870a91c4686c3d9

**Comment by grachevko** [comment]
2 ч. нахуй
