### ISSUE TITLE
Резервирование запчастей

### ISSUE THREAD

**Issue by grachevko** [automagistre/automagistre#2]
- [ ] Где и в при какие условиях надо резервировать запчасти
- [ ] Что делать, если на складе оказалось меньше запчастей чем в резерве (Например уменьшилось фактическое наличие по результатам инвентаризации)
- [ ] Где и как выводить информацию о зарезервированных запчастях
- [ ] В каком формате показывать колонку "Склад" на странице просмотра заказа

**Comment by grachevko** [comment]
https://toster.ru/q/332407

**Comment by KCH0000** [comment]
1. Резервирование запчастей происходит в открытом заказе. Когда запчасть попадает в открытый заказ наряд, она пытается зарезервироваться на со склада. Если на складе недостаточно кол-во для резервирования, то запчасть переходит в разряд заказной. 
2. Оператор в заказе может перевести запчасть из резерва в заказную, либо наоборот из заказной в резерв, если кол-во достаточно.
3. При инвентаризации, если возникла пересортица в меньшую сторону, то при корректировки необходимо запретить списание запчасти, если их кол-во станет меньше, чем зарезервированных. Оператор должен предварительно снять резервы, а после уже вносить корректировку. 
4. В заказе рядом с запчастью должен быть значек, что запчасть зарезервирована, либо нуждается в заказе. Сейчас это галочка, либо круговые стрелочки.
5. При просмотре запчасти должен выводиться весь список заказов, где данная запчасть зарезервирована. Так же на странице запчасти должно отображаться наличие на складе и сколько из наличия в резерве.

**Comment by KCH0000** [comment]
Отображение в заказе.
После названия выводить две колонки 
1. Кол-во необходимое в заказе
2. Доступное количество для резерва. Кол-во на Складе минус количество Резерва. В скобках количество резерва, если оно есть.
3. Если запчасть в строке заказа зарезервирована, то никакой аналитики производить не нужно.
4. Если запчасть в рекомендации или в состоянии заказа, то применяем аналитику и фон.
     а. Необходимое количество меньше или равно Складе минус Резерв. (Н <= С - Р). Применяем зеленый фон.
     б. Необходимое количество меньше или равно, чем на Складе ( Н <= C). Применяем желтый фон. Означает, что можно взять из резерва.
     в. Необходимое количество больше чем на Складе. (Н > С). Применяем розовый фон. Т.е. запчастей не хватает в любом случае.

**Comment by grachevko** [comment]
https://github.com/automagistre/automagistre/commit/d67da5e2e5325a6cba8968fcfe35b3190c5842e9
https://github.com/automagistre/automagistre/commit/12981c82142e383582706c959b3540c9f10bc0e2
