### ISSUE TITLE
Ошибка в расчете общей суммы счет клиента

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#201]
В расчетах общей суммы учитываются гарантийные позиции, из-за чего происходит расхождение в листинге проводок и состояния счета.

**Comment by KCH0000** [comment]
![image](https://user-images.githubusercontent.com/28162151/64065157-a880c600-cc12-11e9-93e1-5445ff1a394d.png)
![Screenshot_20190831_171353](https://user-images.githubusercontent.com/28162151/64065165-c1897700-cc12-11e9-89ea-1f264f872c1f.png)

**Comment by grachevko** [comment]
Проблема только с одним конкретным клиентом из-за ручного слияния двух клиентов через SQL.

**Comment by grachevko** [comment]
Поле subtotal из-за которого была проблема было выпилено, воспроизведение текущей ситуации невозможно.
