### ISSUE TITLE
Создать новый сервис

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#202]
Изолированный автосервис. 
Полное наименование                                          Индивидуальный предприниматель 
                                                                                Щавлев Владимир Алексеевич

Сокращённое наименование                                ИП Щавлев В.А.

Юридический адрес                                             142660   Моск. обл, 
                                                                                Орехово-Зуевский район,
                                                                                д.  Малое Кишнево, д.39                                                                     

Фактический адрес                                               142623   Моск. обл., 
                                                                                Орехово-  Зуевский район, 
                                                                                п. Пригородный,                                                                           
                                                                                Малодубенское шоссе, 3 км, цех № 1

Телефон                                                                  8-496-423-43-18,
                                                                                 8-926-214-56-65

e-mail                                                                       smitavtoservis@mail.ru

Руководитель (ИП)	                                        Щавлев Владимир Алексеевич

ИНН                                                                         507303160627

Гос.регистрац. номер                                             304503414800230 от 27.05.2004 г.

ОКПО                                                                       0065503228

ОКВЭД                                                                     50.20

Банковские реквизиты :

Наименование банка                                             ПАО СБЕРБАНК
                                                                                 г. Москва

Расчётный счёт	                                                   40802810940000009848
Кор. Счёт                                                                 30101810400000000225

БИК                                                                           044525225

**Comment by grachevko** [comment]
https://github.com/automagistre/automagistre/commit/13d1587f4d128be8145f60889b73a952c984dc83
