### ISSUE TITLE
Новый дизайн

### ISSUE THREAD

**Issue by grachevko** [automagistre/automagistre#41]
В качестве стартовой страницы нужно взять popup с выбором модели автомобиля и кузова. 
Все ссылки на сайте должны идти с префиксом `automagistre.ru/<марка>-<модель>-<кузов>`, кроме страницы `All brands`.
На этапе выбора марки должна быть кнопка "Другая марка" с переходом на страницу `All brands`.
Скрыть кнопку перехода в магазин, до реализации магазина.

**Comment by KCH0000** [comment]
Пользователь заходит на страницу 00, где выбирает марку или жмет кнопку " у меня другая машина.
1. Если выбирает "У меня другая машина", то переходит на страницу 09. Адрес страницы должен содержать слова Kia Hyundai Mitsubishi Mazda Honda.
2. Если пользователь выбирает автосервис, то он переходит на страницу 01 
под лого должна фигурировать выбранная марка, адрес страницы /service/марка/

Страница 01
1. Диагностика - переход на страницу 03
2. ТО - переход на страницу 06
3. Ремонт - переход на страницу 02
4. Добавить 4й вариант "шиномонтаж" - переход на страницу 05

**Comment by KCH0000** [comment]
Страница 01
1. Диагностика - переход на страницу 03
2. ТО - переход на страницу 06
3. Ремонт - переход на страницу 02
4. Добавить 4й вариант "шиномонтаж" - переход на страницу 05

**Comment by KCH0000** [comment]
с ссылками что-то непонятное пока получается
/service/nissan/
service/to/nissan/qashgai/j10
service/price/podveska/nissan/qashgai/j10
service/tyreservice/
