### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#43]
Ссылка на logo переводит на страницу 00

У пользователя есть возможность быстрого выбора марки комбобоксом под лого. Адрес станицы меняется в соответствии с выбором пользователя /марка/текущая страница

Ссылка "Автосервис в Москве" переход на страницу 01

Ссылка "Магазин запчастей - переход на страницу 19

"Мой гараж" - на данный момент не активна

"Контакты"  - переход  на страницу 20

**Comment by grachevko** [comment]
Всё сделано кроме Магазина, он так же не активен как и гараж до реализации магазина
