### ISSUE TITLE
Получение отзывов по JSON-RPC

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#606]
***Проблема***
  Нет никакого смысла показывать отзывы посредством шаблона, поэтому желательно показывать их на лету, а так же нет смысла выгружать сразу все отзывы

***Задача***
  Нужен метод, которые будет выдавать порционо массив отзывов. Желательно иметь возможно самостоятельно задавать диапазон срез со всего массива отзывов отсортированных по `publish_at`. А так же иметь индикатор того, что далее нет смысла запрашивать новые отзывы.

**Comment by KCH0000** [comment]
Необходима возможность получать отзыва по производителю и по названию машины.

**Comment by grachevko** [comment]
Что такое "название машины"?

**Comment by KCH0000** [comment]
@grachevko это поле 'model' в таблице отзывов. Просто во всей системы под моделью имеется ввиду кузов. 
Например Кашкай J10, Кашкай - название(name), а J10 - кузов (model)

**Comment by grachevko** [comment]
не актуально
