### ISSUE TITLE
Заметки о пользователе / машине

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#71]
Нужно сделать возможность оставлять заметки про пользователя со статусами.
Например
кинул на запчасти статус Warning
Скандалил по какой то фигне  статус ALERT 
Лояльный, делает что скажет статус ОК

были установлены рычаги Фебест Варнинг
Стоит неродная коробка АЛЕРТ

В будущем, когда заказ открывается в нем будут появляться значки соответствущие статусам, при наведении на которые будет всплывать информация о внесенной записи

**Comment by grachevko** [comment]
Заметки готовы https://github.com/automagistre/automagistre/commit/d949083d3dc2680cd17e5c1a3f69b6f9fe486549
А будущее - это когда?
