### ISSUE TITLE
Заметки о машине

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#72]
Аналогично пользователю, только цель вносить особенности автомобиля.
Например 
были установлены рычаги Фебест Варнинг
Стоит неродная коробка АЛЕРТ

Данные заметки должны будут выводиться в заказе и привлекать внимание приемщика, чтобы учел особенности машины при расчетах

**Comment by grachevko** [comment]
Дубль https://github.com/automagistre/automagistre/issues/71
