### ISSUE TITLE
Работа с запчастями

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#74]
Процесс работы с запчастями после момента заказа.
Запчасти приходят  от поставщика группами объединенными документом (счет, накладная, чек). После ответственный человек эти запчасти принимает и оприходует на склад. На данном этапе оператор может допустить ошибки
1. Занести запчасть не в ту нуменклатуру.
2. Не занести запчасть.
3. Замести неверное кол-во.
Видимое решение.
Оператор создает приход, где указывает поставщика (поставщик может быть Noname типа палатка с южки) и вводит номер документа. После забивает позиции из документа с обязательной суммой закупки зч. После для проверки выводится сумма накладной, кол-во позиций и кол-во запчастей. Если все это совпадает с реальным документом, то можно занести на склад.

**Comment by KCH0000** [comment]
Продажа запчастей. Согласно вину подбираются запчасти на машину. Главная проблема в том, что на складе может оказаться позиция, но ее менеджер не может найти, т.к. не знает какой номер, какого прозводителя пробивать на складе. 
Решение. Создать кроссы.  У всех поставщиков кроссы реализованы в одну сторону, т.е. если запчасть А идет по замене к запчасти В, то В не будет идти по замене к запчасти А. Нам нужна двухстороняя зависимость, поэтому предлагается объединять запчасти в группы аналогов(назвать кроссы).

**Comment by grachevko** [comment]
https://github.com/automagistre/automagistre/commit/6319f70d7ff399fb8dddc0cf39b34da8a93a6a89
