### ISSUE TITLE
Место запчасти на складе

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#83]
- [ ] Добавить поле "Место на складе". Обычное текстовое поле.
- [ ] Добавить поле "Место на складе". в форме создания.
- [ ] Добавить поле "Место на складе". в форме редактирования.

теоретически место складе это дерево произвольной глубины например.
Левый склад -> 3-й стелаж -> 2я полка. 
У каждой позиции есть сокращенное название из которых состоит сокращенное название конечной точки типа:
ЛС-3с-2п.

**Comment by KCH0000** [comment]
теоретически место складе это дерево произвольной глубины например.
Левый склад -> 3-й стелаж -> 2я полка. 
У каждой позиции есть сокращенное название из которых состоит сокращенное название конечной точки типа:
ЛС-3с-2п.

**Comment by grachevko** [comment]
Какая то непонятная древняя хуйня, сделаю вид что не видел
