### ISSUE TITLE
Смс с просьбой оставить отзыв

### ISSUE THREAD

**Issue by grachevko** [automagistre/automagistre#855]
В момент закрытия заказа добавить опцию, при выборе которой клиенту на следующий день приходит смс со ссылкой на Яндекс карту с просьбой поставить оценку

**Comment by KCH0000** [comment]
Текст сообщения:
**"Благодарим за выбор нашего автосервиса. Помогите стать лучше, оставив отзыв о нашей работе"**
Согласно статистике из интернетов - нужно отправлять смс не через день, а через час.

**Comment by grachevko** [comment]
https://github.com/automagistre/automagistre/commit/2c676d2cdd005c889c1c66f99e025492f2048b9a
