### ISSUE TITLE
Доработка данных в mongo

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#912]
- [x] Цена у запчастей, сейчас везде 0
~~- [ ] Нет данных о периодичности посещения сервиса для кузова~~
- [x] Нужно добавить поле Unit(единица измерения) для запчасти

**Comment by grachevko** [comment]
Откуда цены брать? Те что текущие в базе? Там же постоянно проёбы себе в минус?)
Период посещения кузова мы вроде вводили для контроля ввода работ, при этом этого контроля сейчас нет и местами есть проёбы.
Поле unit для запчасти какое отношение к монге имеет?

**Comment by KCH0000** [comment]
Цены брать их базы, конечно. По позициям из карт все отлично, и в общем то иначе не может быть.
Хотя, да, забыл что достаточно взять минимальный пробег у работы. Отмена.
Юнит к монге не имеет отношения, но имеет отношение к запчасти. Этого поля нет, но похоже уже должно быть, т.к. оно используется и бух. отчетности и теперь в калькуляторе.
