### ISSUE TITLE
Прием обращений клиентов с сайта

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#913]
Нужен интерфейс отправки и получения обращений клиентов с фронта

Обращение может содержать след поля.

Имя | Телефон |  e-mail | Содержание |

**Имя** - имя клиента, которое указывается на сайте
**Телефон** - телефон клиента, может быть и не указан, разные формы содержат разные поля, на основании телефона можно будет сразу отображать полные данные, клиента, если он у нас был
**E-mail** - аналогично телефону, поле необязательное.
**Содержание** - содержит, то что клиент ввел в форму или накликал в калькуляторе или шиномонтаже. Нужно подумать как обрабатывать такие сообщения для понятного отображения в админке. В общем-то это может быть обычный json, где указан тип, и рисовать верстку в твиге на основании типа.

У обращения должны быть статусы
Статусы:
- Новое - когда еще ни один менеджер не посмотрел.
- В работе - когда менеджер зашел и ознакомился.
- Завершено - работа с обращением завершена.

У обращения должны быть комментарии, где менеджер при попытке обработать обращение будет указывать о результате, например "Недозвонился", "Попросили перезвонить"

Изменение статусов и добавление комментариев логируется с указанием времени и менеджера.

**Comment by grachevko** [comment]
`/api/v1/appeal/calc` - Калькулятор
```json
{
    "name": "bla",
    "phone": "+79261680000",
    "body": [
        "bla"
    ]
}
```

`/api/v1/appeal/schedule` - Запись на дату
```json
{
    "name": "bla",
    "email": "bla@automagistre.ru",
    "date": "2020-01-01"
}
```

`/api/v1/appeal/question` - Задать вопрос
```json
{
    "name": "bla",
    "email": "bla@automagistre.ru",
    "question": "bla bla"
}
```
`/api/v1/appeal/cooperation` - Предложение о сотрудничестве
```json
{
    "name": "bla",
    "phone": "+79261680000"
}
```
`/api/v1/appeal/tire-fitting` - Шиномонтаж
```json
{
    "name": "bla",
    "phone": "+79261680000",
    "body": [
        "bla"
    ]
}
```

**Comment by KCH0000** [comment]
Нужно добавить форму где поля
```json
{
    "name": "bla",
    "phone": "+78888888888",
    "date": "2020-01-01"
}
```

**Comment by KCH0000** [comment]
изменить формат  для
`/api/v1/appeal/calc`
```json
{
    "name": "string",
    "phone": "+79261680000",
    "note": "string",  
    "date": "2020-01-01",  
    "equipment": "uuid", 
    "mileage": 0, 
    "total": 0, 
    "works": [ ] 
  }
```

**Comment by KCH0000** [comment]
изменить формат
`/api/v1/appeal/tire-fitting`
```json
{
    "name": "",  // Name in form
    "phone": "", // Phone in form
    "model": "", // id model if available
    "diameter": 0, // diameter of tires
    "carType": "", // Selected car type
    "total": 0, // Total cost of order
    "works": [ ] // selected works
  }
```

**Comment by KCH0000** [comment]
На данный момент все реализовано.
