### ISSUE TITLE
Пауза заказа

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#95]
Фунционал поставить заказ на паузу.
Пользователь заходит на страницу заказа нажимает кнопку пауза и ему предлагается форма
1. Указать дату ДО которой заказ находится на паузе.
2. Вводит причину паузы ( обязательно), типа недозвонился, выбирает время и прочее.

После того, как пользователь нажимает ОК
1. Причина записывается, как комментарий к заказа "Пауза: {{ причина }}"
2. В списке заказов не зависимо от статуса отображается серым цветом.

в 7:00 указанной даты пауза снимается, заказ начинает отображаться в соответсвии со статусом. в комментариях к заказу записывается "Заказ возобновлен"

**Comment by grachevko** [comment]
Суть функционала в чём? Отображать серый статус на время действия паузы?

**Comment by KCH0000** [comment]
Визуально да. Это гарантийрованный период, когда с заказом не требуется каких либо действий.
Например уведомил клиента, он как всегда в ебенях и просит напомнить через две недели. Статус от этого не меняется и остается "Уведомление" но теперь понятно, когда это нужно сделать.

**Comment by grachevko** [comment]
https://github.com/automagistre/automagistre/commit/4fce83ee1578236946fccee716f44da716a9fbdf
