### ISSUE TITLE
Добавить индикация "опубликовано"

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#950]
В разделе комплектации добавить столбец с индикацией  о публикации комплектации(да/нет)

**Comment by grachevko** [comment]
На списке?

**Comment by KCH0000** [comment]
Да в списке, и наверное нам надо всех переключить в "не опубликовано" и постепенно публиковать.

**Comment by grachevko** [comment]
ну пиздец, оно было не опубликовано по умолчанию, я вчера специально телодвижения делал чтобы их опубликовать)

**Comment by KCH0000** [comment]
Хуевые решения на скорую руку они такие)
