### ISSUE TITLE
Сортировка и создание отзывов

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#970]
![image](https://user-images.githubusercontent.com/28162151/103127776-f3460d00-46a3-11eb-921f-3e1f9d5e1314.png)
тут проблемка. Я добавил два новых отзывал с 2GIS. Один старый , другой новый, источник указал 2GIS. Но гкл возвращает порядок согласно uid.  Еще когда добавлял в форме обязательным стоит марка и тачка. Щас это не актуально

**Comment by grachevko** [comment]
Для 2GIS надо доступ запросить https://github.com/automagistre/automagistre/issues/986
Сортировку в GraphQL поправилhttps://github.com/automagistre/automagistre/commit/36db8fe705041f7ea72f7030ee27b255f43c3162
Для неактуальных полей открыл отдельную задачу https://github.com/automagistre/automagistre/issues/987
