### ISSUE TITLE
Приходы Движения

### ISSUE THREAD

**Issue by KCH0000** [automagistre/automagistre#99]
- [ ] В комментарии к движению запчасти писать {{ документ }} {{ Поставщик }}
- [ ] При ручном списании, помментарий проводки и зч Ручное списание(пополнение) {{текущий пользователь}}

**Comment by grachevko** [comment]
От комментариев в данном виде уже можно избавится. 
То что это именно проводка по поставке зашито на уровне записи в базе и таблице. На основе чего я могу и так написать что это за проводка, без генераторов описаний. 
Описание сейчас ценное только в одном случае, если туда надо ручками что-то кастомное забить
